//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36365
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQDevApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQDevApplication.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Stocks.
        /// </summary>
        public static string AllStocksViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllStocksViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new stock.
        /// </summary>
        public static string MainWindowViewModel_Command_CreateNewStock {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all Funds.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllFunds {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Stocks.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllStocks {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eq Dev for Fund Manager.
        /// </summary>
        public static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is missing. Must be positive number..
        /// </summary>
        public static string Stock_Error_MissingPrice {
            get {
                return ResourceManager.GetString("Stock_Error_MissingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity is missing. Must be positive number..
        /// </summary>
        public static string Stock_Error_MissingQuantity {
            get {
                return ResourceManager.GetString("Stock_Error_MissingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stock.
        /// </summary>
        public static string StockViewModel_DisplayName {
            get {
                return ResourceManager.GetString("StockViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is missing.
        /// </summary>
        public static string StockViewModel_Error_MissingStockType {
            get {
                return ResourceManager.GetString("StockViewModel_Error_MissingStockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid stock..
        /// </summary>
        public static string StockViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("StockViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond.
        /// </summary>
        public static string StockViewModel_FundTypeOption_Bond {
            get {
                return ResourceManager.GetString("StockViewModel_FundTypeOption_Bond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        public static string StockViewModel_FundTypeOption_Equity {
            get {
                return ResourceManager.GetString("StockViewModel_FundTypeOption_Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund Type.
        /// </summary>
        public static string StockViewModel_FundTypeOption_FundType {
            get {
                return ResourceManager.GetString("StockViewModel_FundTypeOption_FundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string StockViewModel_StockTypeOption_NotSpecified {
            get {
                return ResourceManager.GetString("StockViewModel_StockTypeOption_NotSpecified", resourceCulture);
            }
        }
    }
}
